version: '2'
services:
  ngzorro-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/ngzorro/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ngzorro
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
